### ISSUE TITLE
Not Exporting Tables

### ISSUE THREAD

**Issue by mdlong** [nicogis/Geodatabase-Diagrammer#1]
I am extremely excited to see that someone has decided to continue development on a great tool that Esri seems to have forgotten about.  Thank you.

The tools doesn't seem to be exporting Tables  Feature classes and Relationship classes worked perfectly.
[GeodatabaseDiagram.zip](https://github.com/nicogis/Geodatabase-Diagrammer/files/503376/GeodatabaseDiagram.zip)

Thanks!

-Mike

**Comment by nicogis** [comment]
Hi Mike, can you give me further details (a sample gdb and print screen problem) ?
