### ISSUE TITLE
Difficulties with install

### ISSUE THREAD

**Issue by markchilcott** [nicogis/Geodatabase-Diagrammer#10]
Having difficulties with install.
“GeodatabaseDiagrammer.esriAddIn” not in the unzip folder.

**Comment by oregonGIS** [comment]
I am having the same issue, can the “GeodatabaseDiagrammer.esriAddIn” file be uploaded?

**Comment by markchilcott** [comment]
I did work this out.  Go back to the Code tab (top left of page)
There is a 'Releases' link - click on that.
Download the release from here.
