### ISSUE TITLE
Hash value

### ISSUE THREAD

**Issue by jheec** [nicogis/Geodatabase-Diagrammer#13]
Not truly an issue. Would you please post a hash, MD5, SHA256, or SHA1, for the compiled executable? We wish to use this software, but we need to verify the file we are using matches the one that you have published.

**Comment by nicogis** [comment]
MD5                                     SHA-1
-------------------------------------------------------------------------
a5b3f6a91101de9827f3a29a82cf462c be931f411757f7f75aa5299780ecc80c98898132 geodatabasediagrammerv105.zip
