### ISSUE TITLE
Possible to work with 10.6?

### ISSUE THREAD

**Issue by kestes7000** [nicogis/Geodatabase-Diagrammer#14]
Possible to work with 10.6?

**Comment by markchilcott** [comment]
And possible to with 10.7?

**Comment by nicogis** [comment]
Yes, because this version https://github.com/nicogis/Geodatabase-Diagrammer/releases/tag/v10.5 is compiled in 10.5

**Comment by kestes7000** [comment]
Thanks Nico.
It is awesome that you have kept the diagrammer going!  Thanks so much for
sharing.

Am I missing the "GeodatabaseDiagrammer.esriAddIn" in the zip file or is
the intention for users to compile on their own?   I currently do not have
Visual Studio available to perform the compile myself so just thought I
would inquire.

Thanks again

**Comment by markchilcott** [comment]
Click the code tab (top left)
You will see there is a link to 'releases'
There is a v10.5 -  here you will find the GeodatabaseDiagrammerV105.zip
This file has the .esriAddIn

**Comment by kestes7000** [comment]
Got it!  Thanks
