### ISSUE TITLE
Error with ArcCatalog 10.6.1 and SDE Database

### ISSUE THREAD

**Issue by alexmahrou** [nicogis/Geodatabase-Diagrammer#15]
![image](https://user-images.githubusercontent.com/10987392/75369369-8e056d80-5880-11ea-934e-af8215c375b6.png)

![image](https://user-images.githubusercontent.com/10987392/75369317-76c68000-5880-11ea-8179-f68bdb30ce16.png)
Any Idea what's going on?

**Comment by nicogis** [comment]
Have you installed visio pro 2016 or 2019 32bit ?

**Comment by svHatch** [comment]
I have Visio pro 2016 64 bit. Does it require 32 bit?

**Comment by nicogis** [comment]
Yes, it's in a process 32 bit (ArcCatalog)

**Comment by nicogis** [comment]
... and minimum Version .NET framework 4.6.1 (downloads now because I have recompile with target 4.6.1)
