### ISSUE TITLE
ArcCatalog crashes on open after install of addin

### ISSUE THREAD

**Issue by markchilcott** [nicogis/Geodatabase-Diagrammer#16]
ArcCatalog now crashes when open.  How do I remove the addin?

**Comment by nicogis** [comment]
From ArcCatalog - > menu _Customize_ - > item _Add- in Manager_
select add-in _Geodatabase Diagrammer_  and then click on button **Delete this add-in**

**Comment by markchilcott** [comment]
Thank for feed back - but it is not possible to get to the menu, when the application has crashed.

**Comment by nicogis** [comment]
You can remove this folder C:\Users\ _nameUser_ \Documents\ArcGIS\AddIns\Desktop10.5 \ {bbf7ae19-151b-4ebf-b819-c2263719f31b}
