### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by Dano001** [nicogis/Geodatabase-Diagrammer#17]
i followed the installation instructions, and when i run the tool i get this error:
![GDB_Diagrammer_error](https://user-images.githubusercontent.com/26577405/114870001-44961b80-9dbd-11eb-9131-3be261f1bd6a.PNG)

**Comment by nicogis** [comment]
Are you using ?
ArcGIS Desktop version 10.7.1 or superior
Microsoft Visio Pro 2016-2019 32bit

**Comment by Dano001** [comment]
ArcGIS 10.7.1

***@***.***D731CB.B59B60A0]

**Comment by nicogis** [comment]
An Visio ?

**Comment by Dano001** [comment]
***@***.***D731CC.28A76F30]
MS Visio Plan 2 MSO (16.0.13901.20366) 64-bit

**Comment by nicogis** [comment]
Unfortunately it isn't supported. You need Visio Pro 32bit because ArcGIS Desktop is 32bit
