### ISSUE TITLE
Creating the Diagram Stalls or Takes Too Long

### ISSUE THREAD

**Issue by Tenorbro** [nicogis/Geodatabase-Diagrammer#18]
Following the setup procedure, I am stalled at the creating the diagram step for multiple hours now. Are there cases where this tool does take a long time to complete with the database schema is heavily modified?

**Comment by nicogis** [comment]
It is difficult to answer this question. Are there any errors? Is the diagram eventually generated? Do you have an example to verify the problem? Consider that the program is 32-bit and single thread.

**Comment by Tenorbro** [comment]
Thank you @nicogis I was able to eventually produce a diagram. Only after force closing ArcCatalog I received a security warning prompt that appeared from the Visio program. I believe this occurred due to the External App Links setting in the Visio Trust Center. Once I accepted, I was able to open the diagram. 

I am attempting again and I have the "creating the diagram" status. I can see the file is made in the folder with 0 bytes right now. No errors or anything like that as of now. The only difference this time is I've selected the "use the field metadata information..." option. Otherwise, I don't know how the tool is progressing over the past hour. The schema for this database is  intricate, so I assumed it would be a fast process.

<img width="240" alt="image" src="https://user-images.githubusercontent.com/101267346/228888721-ccf15cba-df3f-41d4-a11a-58d37bbcc735.png">

Edit: This is what I can watch to know the diagrammer is running.
<img width="377" alt="image" src="https://user-images.githubusercontent.com/101267346/228908134-619c2618-e306-45cb-9c63-44e46f42db73.png">

**Comment by nicogis** [comment]
I can add a log file so you can see the progress.
Next days I try set it.

**Comment by Tenorbro** [comment]
Great, thank you. Can you also help me with understanding the RPC server how that is import to this process? I recieved a "RPC Server Fault" at the conclusion of recreating the diagram.

![image](https://user-images.githubusercontent.com/101267346/229225321-26566e8c-0683-4b9e-a00a-f50b3edaee23.png)
![image](https://user-images.githubusercontent.com/101267346/229225446-c65861b2-ef9d-4e68-a427-e44728031727.png)

**Comment by nicogis** [comment]
What version are you using of arcgis desktop ?
What version are you using of Visio? Remember that need version Visio Pro 32bit

**Comment by Tenorbro** [comment]
I utilize argis desktop v10.8.1 and Microsoft® Visio® Plan 2 MSO (Version 2302 Build 16.0.16130.20332) 32-bit.

**Comment by nicogis** [comment]
You need Visio Pro 2016-2019  32bit

**Comment by sqarmout** [comment]
Hi, I've performed all the requirements:
-visio pro 2019 32 bit
- .net framework 4.6.1
- I have ArcGIS 10.8.1
But could not succeed to generate the diagram, please I am in dire need to this diagram, even if somebody can just create the diagram for me and I will send him/her the Schema geodatabase
![Capture](https://github.com/nicogis/Geodatabase-Diagrammer/assets/142967715/847cd887-9d21-4698-bfee-f1ff35bc323d)
![Capture2](https://github.com/nicogis/Geodatabase-Diagrammer/assets/142967715/d982dac7-5660-47d5-94e8-540715fa3a8b)

**Comment by sqarmout** [comment]
Dear @Tenorbro 
are you still using this AddIn?
Can you please help me just produce the schema if I provide you the geodatabase?

**Comment by nicogis** [comment]
try and see https://learn.microsoft.com/en-us/answers/questions/258475/unable-to-cast-com-object-of-type-microsoft-office
