### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by epekcan** [nicogis/Geodatabase-Diagrammer#2]
![image](https://cloud.githubusercontent.com/assets/22872165/19419265/8c563332-93dc-11e6-8fa3-ac3aab316117.png)

**Comment by epekcan** [comment]
Dear Nico, first of all thank you for great support and that tools working perfectly..just you should do some necessary settings correctly. So i am attaching reference document which was prepared for old version GDB Diagrammer.
Again i really appreciate.

[Readme.pdf](https://github.com/nicogis/Geodatabase-Diagrammer/files/531985/Readme.pdf)

**Comment by nicogis** [comment]
Readme.pdf is in download http://www.arcgis.com/home/item.html?id=a378b48be11b45b5bb25254643304cb7
I have only recompiled this version for 10.4 & Visio 2016
What's the problem in print screen ?

**Comment by nicogis** [comment]
I haven't understood print screen: VisioDiagram.vb file exists in repository. What's the problem ?
