### ISSUE TITLE
Not working with ArcGIS 10.4.1 and Visio 2010

### ISSUE THREAD

**Issue by Asrujit** [nicogis/Geodatabase-Diagrammer#3]
I followed the steps, however get the below error while trying to Generate Diagram:
![image](https://cloud.githubusercontent.com/assets/23010286/19625453/8bb79ba6-9921-11e6-96bb-5cd3287df65b.png)

![image](https://cloud.githubusercontent.com/assets/23010286/19625459/c5ba125c-9921-11e6-9406-1b116c4bcd79.png)

I understand that the steps you mentioned and the files may not be compatible with Visio 2010, however any suggestion will be appreciated.

Regards,
Asrujit

**Comment by nicogis** [comment]
You try and get the version 14. 
Add reference > Browse > C: > Windows > assembly > GAC > Microsoft.Office.Interop.Visio > 14.0.0.0_etc > Microsoft.Office.Interop.Visio.dll

**Comment by Asrujit** [comment]
well instead of trying to troubleshoot further, I somehow got the Visio 2016 configured and that is working as expected. Thank you for your time again!
