### ISSUE TITLE
Can't generate diagrams

### ISSUE THREAD

**Issue by darctur** [nicogis/Geodatabase-Diagrammer#4]
Hi, I'm so glad you're keeping this diagrammer updated!!   However, I'm consistently getting errors trying to diagram my databases, and I suspect an installation configuration problem. I'm running ArcGIS 10.4.1, Visio Standard 2016, and installed your diagrammer per instructions, including vss/vst file folder.  Here are some representative error messages; I quit saving them after several went by. The program ends saying "Diagram Complete" but there is no diagram. I can upload the gdb if you like (25mb zipped). 

Thanks, darctur

![gdbdiagrammer error 1-20161105](https://cloud.githubusercontent.com/assets/2423101/20046942/0addbb00-a475-11e6-93c3-d17dd6a55734.png)
![gdbdiagrammer error 2-20161105](https://cloud.githubusercontent.com/assets/2423101/20046949/14e03e5c-a475-11e6-8ca6-449a5d40bc56.png)
![gdbdiagrammer error 3-20161105](https://cloud.githubusercontent.com/assets/2423101/20046953/1b94adbe-a475-11e6-92c2-7b9793cb3085.png)
![gdbdiagrammer error 4-20161105](https://cloud.githubusercontent.com/assets/2423101/20046957/2168266c-a475-11e6-9022-ae7ef36e5ac2.png)

**Comment by nicogis** [comment]
Have you installed visio 32 or 64 bit ?

**Comment by darctur** [comment]
I think it installed 32 bit, how would I tell? 

Thanks, 
dka
—

On Nov 8, 2016, at 10:13 AM, Domenico Ciavarella notifications@github.com wrote:

Have you installed visio 32 or 64 bit ?

**Comment by nicogis** [comment]
https://support.office.com/en-us/article/What-version-of-Office-am-I-using-932788b8-a3ce-44bf-bb09-e334518b8b19

Attach your gdb so I try and see the problem

**Comment by darctur** [comment]
Thanks, I'll check on that later tonight. I'm pretty sure I have 32 bit installed. My smallest version of this gdb is too big to drop in, I'll shrink it tonight too.  Could you tell me if your diagrammer expects to find Visio Standard or Visio Professional?

**Comment by nicogis** [comment]
I'm using Visio Professional 32bit

**Comment by darctur** [comment]
Ok, I definitely have Visio Standard 2016, 32-bit. You may be using some Visio Pro libraries that can handle UML or other database schema representations.   If you can process this gdb, then I need to get the Visio Pro version. I do have Visio Pro 2013, in case you can recompile for that version.  Here's the gdb.  Thanks for your help!
[twm2016_schema.gdb.zip](https://github.com/nicogis/Geodatabase-Diagrammer/files/579539/twm2016_schema.gdb.zip)

**Comment by Asrujit** [comment]
I tried and it worked fine for me...I am attaching the VSD file if that helps.

I'm using Visio Professional 64-bit and ArcGIS 10.4 and 10.4.1. Works for both.

[GeodatabaseDiagram.zip](https://github.com/nicogis/Geodatabase-Diagrammer/files/581004/GeodatabaseDiagram.zip)

**Comment by darctur** [comment]
Ok thanks, I should’ve done a little more research before purchasing that version of Visio.

**Comment by darctur** [comment]
So are you using Visio Pro 64-bit or 32-bit?  You’ve said both now.

**Comment by Asrujit** [comment]
I was referring to ArcGIS 10.4 and 10.4.1, when I said 'both'. I'm using Visio Professional 64-bit.
Sorry for that confusion.

But anyway, Nico is using Visio Pro 32-bit...so seems 32-bit or 64-bit won't be a factor.

**Comment by nicogis** [comment]
[GeodatabaseDiagram.zip](https://github.com/nicogis/Geodatabase-Diagrammer/files/581658/GeodatabaseDiagram.zip)
I have generated your gdb in diagram with Visio Pro 32bit. My machine has created diagram in about 4 minutes

**Comment by darctur** [comment]
Thanks again. The key is having Visio Pro instead of Visio Standard. That’s fine. I’m able to work now. :)
