### ISSUE TITLE
Geodatabase Diagrammer ArcGIS 10.4.1 with Visio Std 2010

### ISSUE THREAD

**Issue by cgsambol** [nicogis/Geodatabase-Diagrammer#6]
I am also having this same issue, although I am using 10.4.1.  Instead of a screenshot i just listed the text in the error message below.
 
Error: GeodatabaseDiagrammer.ViosoDiagram.OpenVisionDrawing(StraingfileName, String pathName) at GeodatabaseDiagrammer.ViosoDiagram.StartDiagram(String cPathName, String strVisioOutputFile) in C:\Temp\StudioAT\ArcGIS\RepositoryGitHub\GDBDiagrammer\SourceCode\Helpers\VisioDiagram.vb:line80 Msg: Could not load file or assembly 'Microsoft.Office.Interop.Visio, Version=15.0.0.0, Culter=neutral, PublicKey Token=71e9bce111e9429c' or one of its dependencies. The system cannot find the file specified.
 
I love this tool and have relied on it for may years to discuss detailed GIS layer design options with non-GIS or non-technical staff. I have just upgraded my ArcGIS desktop to 10.4.1 Geodatabase Diagrammer version from github, and I have Visio Standard 2010. I have downloaded the 10.4.1 version. I have moved the stencils to the proper location and ensured that the paths are pointing to these locations, however I am still getting an error and am not sure what I am missing. I have also opened the templates and resaved them if prompted to the current version of Visio.  Please help, as I love this tool! 

Thanks in advance.

**Comment by nicogis** [comment]
Can you use Visio 2016 Pro (version 15) ?  see https://github.com/nicogis/Geodatabase-Diagrammer/issues/3

**Comment by nicogis** [comment]
see https://github.com/nicogis/Geodatabase-Diagrammer/issues/3

**Comment by cgsambol** [comment]
I see that we have a version of 2013 Std, just have to check on the licensing of it before I can install it.  When I check the licensing for the 2013 I will inquire about Visio 2016 Pro.  Does it Visio 2016 have to be Pro or can it be Standard?  Do you know if 2013 Standard might work?  Thanks for the help.

**Comment by nicogis** [comment]
seems only Visio 2016 Pro . See https://github.com/nicogis/Geodatabase-Diagrammer/issues/4

**Comment by cgsambol** [comment]
Thanks for checking.  I'll have to put a PO in for Visio Pro 2016.  My fingers are crossed that it will get approved.
