### ISSUE TITLE
Visio 2016 compatibility

### ISSUE THREAD

**Issue by azinsharaf** [nicogis/Geodatabase-Diagrammer#7]
Since Visio Pro 2016 can not be installed alongside of O365, does GDB-Diagrammer support Click-to-Run Perpetual release for Visio 2016?

**Comment by nicogis** [comment]
try and see https://support.microsoft.com/en-us/help/3157564/office-click-to-run-perpetual-c2r-p-release-for-project-2016-and-visio

**Comment by azinsharaf** [comment]
Thanks but have you tested it? I need to make sure it works with C2R-P before ordering the license.

**Comment by nicogis** [comment]
I don't know but if it's Visio 2016 Pro it runs . In link I see "... The new Office Deployment Tool supports four new ProductIDs that allow the customers to download and install the standard or Professional versions of Project 2016 and/or Visio 2016 ..."
