### ISSUE TITLE
Compatibility with visio 2016 pro and 10.5.1

### ISSUE THREAD

**Issue by rick-wheeler** [nicogis/Geodatabase-Diagrammer#8]
Should the version posted here work with Visio 2016 Pro and 10.5.1?
I cannot get it to work.

Where is the GeodatabaseDiagrammer.esriAddIn file referred to in the setup instructions as follows?

Double‐click the file “GeodatabaseDiagrammer.esriAddIn”.

Thanks

**Comment by nicogis** [comment]
here https://github.com/nicogis/Geodatabase-Diagrammer/releases
