### ISSUE TITLE
Issue using diagrammer with ArcGIS 10.5.1 and Visio 2016 Online Plan 2 (Professional)

### ISSUE THREAD

**Issue by mgg-eagle** [nicogis/Geodatabase-Diagrammer#9]
Hi there, I have installed the diagrammer add-in and followed the instructions.  I tried to create a diagram and got the following error:
![image](https://user-images.githubusercontent.com/16143861/39730214-6c2d25c8-52b4-11e8-94bb-5ee7abad2479.png)

and when I close that error I get this error:
![image](https://user-images.githubusercontent.com/16143861/39730342-24dad318-52b5-11e8-93cd-61c35ca98d28.png)

then these errors:
![image](https://user-images.githubusercontent.com/16143861/39730351-36b4ec90-52b5-11e8-8d6c-41e235e8c9ba.png)

![image](https://user-images.githubusercontent.com/16143861/39730367-4f2c75d6-52b5-11e8-9442-75a742a36794.png)

I can't close them and have to restart ArcCatalog

Thanks,
Marc

**Comment by nicogis** [comment]
I have tested only with Visio Professional 2016. Visio 2016 Online Plan 2 is not supported from Geodatabase Diagrammer
